### PR TITLE
Feature filter  by tags

### LINKED ISSUE #4: Tags Filtering support
### Motivation

Filtering according to the tags would be beneficial for better user experience

### Proposed solution

Design should be similar to categories filter.

### Additional context

There is tag property in the MarketplaceItemModel.
`    "tags": [
      "mvc",
      "youtube",
      "video",
      "inline-editor"
    ]`

### PR DESCRIPTION
**Pull request by MSharifi78**
It fixes #4

### CODE REVIEW

**Comment by Simply007** [comment]
Great work @MSharifi78!

Would it be possible to make the tag filter expandable and collapsed by default? It looks huge on the preview:
https://deploy-preview-12--ems-extension-marketplace.netlify.com/

Or do you think the multiple selection dropdown would be more intuitive? 

We are using the marketplace here:
https://devnet.kentico.com/marketplace

**Comment by Simply007** [comment]
I have found a couple of multiple selection controls

I think that one looks pretty good: https://vue-multiselect.js.org/

But let's wait for an opinion from @makma - tha main maintainer

**Comment by makma** [comment]
I really like https://vue-multiselect.js.org/, in my opinion, it's much more clear, what do you think @MSharifi78 ?

**Comment by MSharifi78** [comment]
I agree with @makma, it's a popular package with nice API.
I'll use it for tags filter

**Comment by makma** [comment]
Thank you @MSharifi78, I'm looking forward to your updated PR!

**Comment by makma** [comment]
I'm closing this one due to inactivity. Feel free to reopen/submit a new one.

**Pull request closed without merging**
