### PR TITLE
Added Fisher-Yates algorithm to shuffle all items before initialising the store

### LINKED ISSUE #13: Randomise extension ordering
### Motivation

Currently it looks like the listings are being ordered alphabetically from A-Z.  However, by doing this you're prioritising and endorsing the extensions that are at the beginning of the alphabet.

When there are a larger number of extensions, visitors may not click the "Load More Extensions" X number of times to find a widget that begins with Z for example, meaning this widget may never be seen and downloaded.

### Proposed solution

Apply a random order to the listing when initially loaded, and when filters are applied.  When "Load More Extensions" is clicked, the same order of items should be kept.

### PR DESCRIPTION
**Pull request by liamgold**
### Motivation
Fixes #13 

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Comment by petrsvihlik** [comment]
you deployed a wrong branch @makma ...we lost the detail pages. 
this link stopped working: https://devnet.kentico.com/marketplace/ckeditor4%20wysiwyg%20editor

**Comment by liamgold** [comment]
> Hi @liamgold, thank you for implementing this - it looks really good 🎉. I'm going to deploy it on production today.
> 
> Just FYI: In case you are interested, I've also created a new issue #36 for alphabetical ordering ;).

Thanks, I might do in the future!

> you deployed a wrong branch @makma ...we lost the detail pages.
> this link stopped working: https://devnet.kentico.com/marketplace/ckeditor4%20wysiwyg%20editor

Isn't the problem that master doesn't include the changes for PRs #14 through to #32 ?

**Comment by makma** [comment]
Yes @liamgold, my bad, you are right, it'll be fixed within an hour.

**Comment by makma** [comment]
Thank you @liamgold for letting me know. I've merged #34 into master and deployed a new version with both - shuffling and detail pages feature on the production server.

**Pull request merged**
